import pandas as pd
import logging
import os
from datetime import datetime, date
from typing import List, Optional
from sqlalchemy.orm import Session
from sqlalchemy import func

from Databases.app_data_db_connection import get_session, create_connection, init_database
from Databases.webhook_models import WebhookExecutionLog
from Services.notification_service import WebhookNotifier

logger = logging.getLogger(__name__)

class DailyReportGenerator:
    def __init__(self):
        self.notifier = WebhookNotifier()
        self.temp_dir = "reports_temp"
        if not os.path.exists(self.temp_dir):
            os.makedirs(self.temp_dir)

    def generate_daily_reports(self, target_date: Optional[date] = None):
        """
        Generates and sends daily reports for a specific date.
        If target_date is None, defaults to today.
        """
        if target_date is None:
            target_date = date.today()

        logger.info(f"Starting daily report generation for {target_date}")
        
        # Ensure DB connection is initialized
        create_connection()
        init_database()
        
        db = get_session()
        try:
            # 1. Fetch all unique RA emails that had activity today
            ra_emails = db.query(WebhookExecutionLog.ra_email).filter(
                func.date(WebhookExecutionLog.timestamp) == target_date,
                WebhookExecutionLog.ra_email != None
            ).distinct().all()
            ra_emails = [r[0] for r in ra_emails]

            # 2. Process RA Reports
            for ra_email in ra_emails:
                self._process_ra_report(db, ra_email, target_date)

            # 3. Process Individual (Non-RA) Reports
            # Fetch users who are NOT part of an RA report (ra_email is NULL)
            individual_users = db.query(WebhookExecutionLog.user_email).filter(
                func.date(WebhookExecutionLog.timestamp) == target_date,
                WebhookExecutionLog.ra_email == None
            ).distinct().all()
            individual_users = [u[0] for u in individual_users]

            for user_email in individual_users:
                self._process_individual_report(db, user_email, target_date)

            logger.info(f"Daily report generation completed for {target_date}")

        except Exception as e:
            logger.error(f"Error during daily report generation: {e}")
            import traceback
            traceback.print_exc()
        finally:
            db.close()

    def _process_ra_report(self, db: Session, ra_email: str, target_date: date):
        """Generates and sends an Excel report for an RA."""
        logger.info(f"Generating RA report for {ra_email} on {target_date}")
        logs = db.query(WebhookExecutionLog).filter(
            func.date(WebhookExecutionLog.timestamp) == target_date,
            WebhookExecutionLog.ra_email == ra_email
        ).all()

        if not logs:
            return

        filename = f"Daily_Trade_Report_RA_{target_date}.xlsx"
        filepath = os.path.join(self.temp_dir, filename)
        
        # Create DataFrame
        data = []
        for log in logs:
            data.append({
                "Timestamp": log.timestamp.strftime("%Y-%m-%d %H:%M:%S"),
                "User Email": log.user_email,
                "Strategy": log.strategy_name,
                "Symbol": log.symbol,
                "Side": log.side,
                "Status": log.status.upper(),
                "Message": log.message or "N/A"
            })
        
        df = pd.DataFrame(data)
        df.to_excel(filepath, index=False)

        # Send Email
        subject = f"Daily Trade Activity Report - {target_date}"
        html_body = f"""
        <html>
        <body style='font-family: Arial, sans-serif;'>
            <h2 style='color: #007bff;'>Daily Trade Activity Summary</h2>
            <p>Hello RA,</p>
            <p>Please find attached the consolidated trade activity report for all your clients on <strong>{target_date}</strong>.</p>
            <p>This report includes successes, failures, and skipped executions.</p>
            <hr/>
            <p style='color: #6c757d; font-size: 12px;'>Generated by WealthAI Reporting System</p>
        </body>
        </html>
        """
        self.notifier.send_email_with_attachment(ra_email, subject, html_body, filepath, filename)
        
        # Keep file for a while or cleanup later. For now, we'll keep it in temp_dir.

    def _process_individual_report(self, db: Session, user_email: str, target_date: date):
        """Generates and sends a personal Excel report for an individual user."""
        logger.info(f"Generating individual report for {user_email} on {target_date}")
        logs = db.query(WebhookExecutionLog).filter(
            func.date(WebhookExecutionLog.timestamp) == target_date,
            WebhookExecutionLog.user_email == user_email,
            WebhookExecutionLog.ra_email == None
        ).all()

        if not logs:
            return

        filename = f"Daily_Trade_Report_{target_date}.xlsx"
        filepath = os.path.join(self.temp_dir, filename)
        
        data = []
        for log in logs:
            data.append({
                "Timestamp": log.timestamp.strftime("%Y-%m-%d %H:%M:%S"),
                "Strategy": log.strategy_name,
                "Symbol": log.symbol,
                "Side": log.side,
                "Status": log.status.upper(),
                "Message": log.message or "N/A"
            })
        
        df = pd.DataFrame(data)
        df.to_excel(filepath, index=False)

        subject = f"Your Daily Trade Summary - {target_date}"
        html_body = f"""
        <html>
        <body style='font-family: Arial, sans-serif;'>
            <h2 style='color: #28a745;'>Daily Trade Summary</h2>
            <p>Hello,</p>
            <p>Attached is your personal trade summary report for <strong>{target_date}</strong>.</p>
            <hr/>
            <p style='color: #6c757d; font-size: 12px;'>Generated by WealthAI Reporting System</p>
        </body>
        </html>
        """
        self.notifier.send_email_with_attachment(user_email, subject, html_body, filepath, filename)
